# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: nostr party
description: 𓅦 *ੈ✩‧
baseurl: ""
url: https://nostr.party

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: nostr.party
  description:
    - Hello!
    - This tiny website
    - Hosts nostr addresses
  contact:
    nostr: npub1clk6vc9xhjp8q5cws262wuf2eh4zuvwupft03hy4ttqqnm7e0jrq3upup9
    email: hello@nostr.party
  protocol:
    about: https://nostr.com
    apps: https://www.nostrapps.com
    documentary: https://www.youtube.com/watch?v=aA-jiiepOrE

exclude:
  - README.md

include:
  - .well-known

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
